# Generated by Django 4.0.10 on 2024-06-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('loan', 'Loan')], max_length=50),
        ),
    ]
